providers = ["node", "python"]

[phases.setup]
nixPkgs = ["nodejs", "python3", "python311Packages.pip"]

[phases.install]
cmds = [
    "mkdir -p web-app/public/uploads",
    "cd web-app && npm install",
    "pip install -r web-app/requirements.txt",
    "echo 'Python Version during install:' && python3 --version",
    "echo 'Python Path during install:' && which python3"
]

[phases.build]
cmds = ["cd web-app && npx prisma generate && npm run build"]

[start]
cmd = "echo 'PATH at runtime:' $PATH && echo 'Python location at runtime:' && (which python3 || echo 'python3 not found') && cd web-app && npm run start"
