providers = ["node"]

[phases.setup]
nixPkgs = ["nodejs"]
aptPkgs = ["python3", "python3-pip"]

[phases.install]
cmds = [
    "cd web-app && npm install",
    "pip3 install -r web-app/requirements.txt --break-system-packages",
    "python3 --version"
]

[phases.build]
cmds = ["cd web-app && npx prisma generate && npm run build"]

[start]
cmd = "mkdir -p web-app/public/uploads && cd web-app && npm run start"
