get_providers = ["node", "python"]

[phases.setup]
nixPkgs = ["nodejs", "python3", "python311Packages.pip"]

[phases.install]
cmds = ["cd web-app && npm install", "pip install -r web-app/python_requirements.txt"]

[phases.build]
cmds = ["cd web-app && npx prisma generate && npm run build"]

[start]
cmd = "cd web-app && npm run start"
